### ISSUE TITLE
Consider exposing Chance.js methods when no Good Eggs-specific method is defined

### ISSUE THREAD

**Issue by mattpetrie** [goodeggs/fake-eggs#41]
`fake-eggs` does not provide many commonly-needed types of fake data, such as ZIP codes. This results in projects that use `fake-eggs` to commonly use one or more additional fake data libraries to generate types of data not covered in `fake-eggs`. This leads to dependency bloat, and inconsistent usage due to lack of clarity about when to use `fake-eggs` vs. another faking library.

So my suggestion is this:
What if `fake-eggs` wrapped [`faker`](https://github.com/marak/Faker.js/), the extremely popular fake data library that is already commonly in use? `fake-eggs` could supply its own fakes when there are Good Eggs-specific concerns for the data type, and default to the `faker` implementations for every thing else.

This would vastly expand the possible uses of `fake-eggs` without the need to implement additional fake data generators, unless we have a specific opinion on how the data should be faked. It would also eliminate the need for developers to reason about whether they should use `fake-eggs` or `faker` for a specific case, since `fake-eggs` would make that determination for them.

**Comment by serhalp** [comment]
Thanks @mattpetrie. I think to be able to consider these questions effectively, we should answer these questions first: https://github.com/goodeggs/fake-eggs/issues/42.

**Comment by serhalp** [comment]
There's also [this open PR](https://github.com/goodeggs/fake-eggs/pull/39) which makes fake-eggs wrap Change.js under the hood (along with many other good improvements).

**Comment by mattpetrie** [comment]
Follow back up on this now that the (fantastically upgraded) fake-eggs 5.0 is out (🎉 ).

I don't think there's any obvious reason to replace chance.js with faker if we like chance.js. Using chance.js under the hood for fake-eggs addresses one of my main concerns that I was trying to raise here, which is not reinventing the wheel/rolling our own solution when a well-established community solution to the same problem exists. 

However, I think the other suggestion I made here - that we expose all of the other methods from the underlying library that we don't have a Good Eggs-specific version of, is still one worth considering.

Chance.js [exposes many other kinds of fake data generators](https://chancejs.com/index.html) that are potentially useful to us.

I've come to believe their is benefit to having fake-eggs for the convenience of being able to generate Good Eggs-specific data, like foodhubs and product names. However, I think it is commonly believed that the best practice is to use fake-eggs *exclusively*, which leads in many cases to using less-realistic data (such as [this use of fake.number() for a geolocation coordinate](https://github.com/goodeggs/garbanzo/blob/a09846f9e36823d6a77d729570518196c17c8654/src/graphql/data_sources/basket/normalizers/delivery_details/factory.ts#L33), which [chance.js has a specific method for](https://chancejs.com/location/latitude.html)), or using one-off concoctions to simulate the desired data within the constraints of the methods exposed by fake-eggs (such as the `fake.integer(10000,99999).toString()` incantation that was frequently used for ZIP codes before `fake.zip()` was added).

Even if we accept that using fake-eggs exclusively is *not* the best practice, then we have introduced a decision that the developer must make every time fake data is required: whether fake-eggs or some other library would be more appropriate for the fake data, and if not fake-eggs, then what library should be used (to me this is a compelling argument to settle on exclusive use of fake-eggs as the best practice).

By having fake-eggs expose the methods of the underlying generator library we would:
* Ensure all fake data was generated with a consistent, "blessed" library (fake-eggs + whatever it uses under the hood, currently chance.js).
* Empower engineers with [all kinds of new types of fake data](https://chancejs.com/index.html) without the need to introduce dependencies on any other libraries and without having to make decisions about which fake data library to use when.
* Give ourselves the ability to seamlessly change all fake data of a specific type to more Good Eggs-specific data if we arrive at the opinion in the future that that would be useful. For example, if we were to decide that all generated `latitude` and `longitude` coordinates should be within North America, we could do that, an all existing uses of `fake.longitude` (which previously would be a thin wrapper on chance.js `longitude`) would be seamless updated to use the more specific data just by updating the fake-eggs version.

I think this could probably be implemented with minimal code by using a [Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

What do you think @serhalp?
