### ISSUE TITLE
Select better defaults to `fake.date` "from" and "to" params

### ISSUE THREAD

**Issue by shermam** [goodeggs/fake-eggs#49]
The `date` generator, currently have some hardcoded values for the params `from` and `to` [here](https://github.com/goodeggs/fake-eggs/blob/master/src/generators/date/index.ts#L27-L30). This is causing some flaky tests when we do something like this:

```ts
const myDate = fake.date(someOtherRandomDate);
```

What I expect to get back from the call above is that `myDate` would have a value that ranges from `someOtherRandomDate` to the date of the death of the universe or something. But right now if `someOtherRandomDate` ends up being a date before the hardcode `to` default value of `Tue Dec 31 2019 16:00:00 GMT-0800 (PST)` I get the following error:

```
RangeError: Chance: Min cannot be greater than Max.
```

My suggestion would be to set the value to the `to` param, when not provided, to something that is after the `from` param.

**Comment by serhalp** [comment]
Closed by #50.
